### ISSUE TITLE
Datum der Registrierung wird falsch angezeigt

### ISSUE THREAD

**Issue by mrschmock** [LuxXx/agspiel-nodejs-api#1]
Beim Profilaufruf wird das Registrierungsdatum falsch angezeigt,
Beispiel: **WKN 166456**

**Daten aus dem Spiel:**
Spieler-Registrierung | 24.03.2014
AG-Gründungsdatum | 09.06.2017

**Auszug aus dem Profilaufruf:**
regdatum: 2014-03-23T23:00:00.000Z,
agregdatum: 2017-06-08T22:00:00.000Z,

irgendetwas stimmt mit der Formatierung der Daten nicht.

Mit freundlichen Grüßen
mrschmock

**Comment by LuxXx** [comment]
Hi, es kann sein, dass das an der Zeitzone liegt. Du kannst vielleicht selbst 2h drauf rechnen.

`someDate = new Date(someDate.getTime() + 2*60*60*1000);`

**Comment by LuxXx** [comment]
Dieser standard heißt ISO-8601 und das Format ist: YYYY-MM-DDTHH:mm:ss.sssZ

Du kannst `new Date('someISOString')` nutzen, um ein Date-Objekt zu erzeugen.

**Comment by mrschmock** [comment]
WOW... so schnell habe ich die Antwort nicht erwartet.
Ja man kann da Zeit drauf rechnen, vielleicht liegt es an der Sommer und Winterzeit warum einmal 22uhr und einmal 23 Uhr steht... für meine Anzeige brauche ich kein so genaues Datum deswegen habe ich die Rohdaten genommen und die bereite ich mit php wieder auf,

Danke dir für die schnelle Antwort vielleicht hilft es ja dem nächsten der sich fragt warum das Datum falsch ist.
Danke für die coole API, die motiviert mich, sich wieder mehr mit JavaScript zu beschäftigen :D
